/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NsList {
    'items': string[];
  }
  interface NsListItem {}
}

declare global {


  interface HTMLNsListElement extends Components.NsList, HTMLStencilElement {}
  var HTMLNsListElement: {
    prototype: HTMLNsListElement;
    new (): HTMLNsListElement;
  };

  interface HTMLNsListItemElement extends Components.NsListItem, HTMLStencilElement {}
  var HTMLNsListItemElement: {
    prototype: HTMLNsListItemElement;
    new (): HTMLNsListItemElement;
  };
  interface HTMLElementTagNameMap {
    'ns-list': HTMLNsListElement;
    'ns-list-item': HTMLNsListItemElement;
  }
}

declare namespace LocalJSX {
  interface NsList {
    'items'?: string[];
    'onListEmitted'?: (event: CustomEvent<any>) => void;
  }
  interface NsListItem {}

  interface IntrinsicElements {
    'ns-list': NsList;
    'ns-list-item': NsListItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ns-list': LocalJSX.NsList & JSXBase.HTMLAttributes<HTMLNsListElement>;
      'ns-list-item': LocalJSX.NsListItem & JSXBase.HTMLAttributes<HTMLNsListItemElement>;
    }
  }
}


